---

name: 'CI'


on:
  push:
    branches:
      - '**'
    tags:
      - '*'

env:
  GIT_SYNC_URL: "https://${{ secrets.GITLAB_USERNAME_ROBOT }}:${{ secrets.GITLAB_TOKEN_ROBOT }}@gitlab.com/nofusscomputing/projects/centurion_erp.git"

jobs:


  docker:
    name: 'Docker'
    uses: nofusscomputing/action_docker/.github/workflows/docker.yaml@development
    with:
      DOCKER_BUILD_IMAGE_NAME: "nofusscomputing/kubernetes-manifest-tools"
      DOCKER_PUBLISH_REGISTRY: "docker.io"
      DOCKER_PUBLISH_IMAGE_NAME: "nofusscomputing/kubernetes-manifest-tools"
    secrets:
      DOCKER_PUBLISH_USERNAME: ${{ secrets.NFC_DOCKERHUB_USERNAME }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.NFC_DOCKERHUB_TOKEN }}
